name: Send SMS Notification
on:
  push:
    branches:
      - master
jobs:
    send_sms:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install africastalking
            - name: Send SMS Notification
              env:
                  API_KEY: ${{ secrets.AT_API_KEY }}
                  USERNAME: ${{ secrets.AT_USERNAME }}
                  PHONE_NUMBER: ${{ secrets.TO_PHONE_NUMBER }}
              run: |
                  python send_sms.py
