name: Send SMS Notification
on:
  push:
    branches:
      - master
jobs:
    send_sms:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install AT Python SDK
              run: pip install africastalking
            - name: Send SMS
              env:
                  TO: ${{ secrets.TO_PHONE_NUMBER }}
                  MESSAGE: ${{ github.event_name }} on ${{ github.repository }} by ${{ github.actor }}
              run: |
                  import africastalking
                  africastalking.initialize(username='${{ secrets.AT_USERNAME }}', api_key='${{ secrets.AT_API_KEY }}')
                  sms = africastalking.SMS
                  response = sms.send(
                      message='${{ env.MESSAGE }}',
                      recipients=['${{ env.TO }}']
                  )